apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Production release
        - $patch: replace
        image: quay.io/emiliobucha/tekton-reversewords:6457898e9787b0dd8fd86f3848abce592ec1a745
        name: reverse-words
